<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tkcropthumbs"
 *
 * Auto generated by Extension Builder 2013-10-31
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Crop and Square Thumbnails',
	'description' => 'Crop Thumbnails with image area select and has a switch to make thumbs with aspect ratios. Can use it for Detailviews or simple galeries.',
	'category' => 'misc',
	'author' => 'Thomas Kieslich',
	'author_email' => 'info@thomaskieslich.net',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '6.2.3',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2-6.2.999',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);